### PR TITLE
fix: Resolve cyclic import between `fs_core.ts` <-> `fs_fd.ts`

### PR DESCRIPTION
**Pull request by kateinoigakukun**
Close https://github.com/bjorn3/browser_wasi_shim/issues/58

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
Thanks :)

**Comment by bjorn3** [comment]
I just saw https://github.com/ruby/ruby.wasm/pull/332. Looks cool! Do you need a new release or are there still some issues you need fixed first?

**Comment by bjorn3** [comment]
Done as v0.2.17.

**Comment by kateinoigakukun** [comment]
Thanks a lot!

**Comment by kateinoigakukun** [comment]
Just FYI: We released ruby.wasm [2.4.0](https://github.com/ruby/ruby.wasm/releases/tag/2.4.0) and it now uses `@bjorn3/browser_wasi_shim` as default WASI impl for browser. Thank you for your all work!

**Pull request merged**
