### PR TITLE
Shim fd_sync

### PR DESCRIPTION
**Pull request by shritesh**
First of all, a huge thanks for creating this project. I have been using this for about a month with a few additions in a fairly large project (at work) and its been great. After the last few commits, only the remaining two changes are necessary to make it work. 

The `fd_sync` one is trivial. For `fd_seek` on directories, IIUC the return value is supposed to be treated as an opaque value so I return 0 there.

### CODE REVIEW

**Comment by bjorn3** [comment]
I'm happy to hear that this project has been helpful for you.

Adding a nop fd_sync impl makes sense to me. The entire VFS is in-memory anyway. Maybe you could move it to `Fd` directly so that it doesn't have to be implemented for every class that is deriving from `Fd`?

I think fd_seek on a directory returns EBADF in Wasmtime however.

**Comment by shritesh** [comment]
Cool. I've done so. Also removed the incompatible `fd_seek`.

**Comment by shritesh** [comment]
Huh, turns out we didn't need the `fd_seek` on dirs anymore. Everything works correctly as is.

**Comment by bjorn3** [comment]
Released as v0.2.13.

**Pull request merged**
